Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    config.vm.synced_folder  ".", "/vagrant", disabled: false
        config.vm.define "docker" do |master|
            master.vm.network "forwarded_port", guest: 80, host: 80
            master.vm.network "forwarded_port", guest: 81, host: 81
            master.vm.hostname = "docker"
                master.vm.provider "virtualbox" do |vb|
                    vb.memory = 4096
                    vb.cpus   = 2
                end
                master.vm.provision "shell", inline: <<-shell
                    sudo apt-get update
                    sudo apt install -y docker.io docker-compose
                    sudo usermod -a -G docker vagrant
                shell
        end
end 