---
# Master VM

- name: Master Puppet Server
  hosts: master.puppet
  become: true
  tasks:

    - name: GPG key add
      rpm_key:
        key: https://yum.puppet.com/RPM-GPG-KEY-puppet-20250406
        state: present

    - name: Install official Puppet repository
      yum:
        name: https://yum.puppet.com/puppet-release-el-8.noarch.rpm
        state: present

    - name: Install packages
      yum:
        pkg:
        - puppetserver
        - git
        - mc
        state: present

    - name: install r10k    
      gem:
        executable: /opt/puppetlabs/puppet/bin/gem
        name: r10k
        user_install: false
        state: present

    - name: Create dir for r10k config
      file:
        path: /etc/puppetlabs/r10k
        state: directory

    - name: Create config r10k
      copy:
        dest: /etc/puppetlabs/r10k/r10k.yaml
        content: | 
          ---
          :cachedir: '/var/cache/r10k'
          :sources:
            :my-org:
              remote: 'https://github.com/arraktur/Puppet-demo.git'
              basedir: '/etc/puppetlabs/code/environments'

    - name: Change memory use
      replace:
        path: /etc/sysconfig/puppetserver
        regexp: '-Xm(s|x)2g'
        replace: '-Xm\g<1>256m'

    - name: Creating a file autosign.conf
      copy:
        dest: /etc/puppetlabs/puppet/autosign.conf
        content: |
          slave1.puppet
          slave2.puppet

    - name: Edit hosts    
      blockinfile:
        dest: /etc/hosts
        block: |
         - '192.168.210.152 slave1.puppet'
         - '192.168.210.153 slave2.puppet'

    - name: ADD host puppetserver
      ini_file: 
        path: /etc/puppetlabs/puppet/puppet.conf
        owner: root
        group: root
        mode: '0644'
        section: agent
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
      - { option: "server", value: "master.puppet" }
      - { option: "autosign", value: "true" }

    - name: Start puppetserver daemon
      service:
        name: puppetserver
        state: started
        enabled: true

    - name: Deploy r10k environment
      shell: /opt/puppetlabs/puppet/bin/r10k deploy environment -p

#Slave VM

- name: Slave Puppet
  become: true
  hosts:
    - slave1.puppet
    - slave2.puppet
  
  tasks:

    - name: GPG key add
      rpm_key:
        key: https://yum.puppet.com/RPM-GPG-KEY-puppet-20250406
        state: present

    - name: Install official Puppet repository
      yum:
        name: https://yum.puppet.com/puppet-release-el-8.noarch.rpm
        state: present

    - name: Install puppet agent
      yum:
        pkg: puppet-agent
        state: present

    - name: Add master.puppet to /etc/hosts
      lineinfile: 
        path: /etc/hosts
        line: '192.168.210.151 master.puppet'

    - name: Restart sshd
      service:
        name: sshd
        state: restarted    

    - name: Agent settings
      ini_file: 
        path: /etc/puppetlabs/puppet/puppet.conf
        owner: root
        group: root
        mode: '0644'
        section: agent
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      with_items:
      - { option: "server", value: "master.puppet" }
      - { option: "runinterval", value: "1m" }

    - name: Enable puppet
      service:
        name: puppet
        state: started
        enabled: true
