Vagrant.configure("2") do |config|
    config.vm.box = "generic/centos8s"
    config.vm.synced_folder ".", "/vagrant", disabled: false
  
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus   = 1
    end
  
    config.vm.define "slave1.puppet" do |slave|
      slave.vm.network "private_network", ip: "192.168.210.152"
      slave.vm.hostname = "slave1.puppet"
      # slave.vm.network "forwarded_port", guest: 80, host: 8080
  
      slave.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "playbook.yaml"
        ansible.become = true
      end
    end
  
    config.vm.define "slave2.puppet" do |slave|
      slave.vm.network "private_network", ip: "192.168.210.153"
      slave.vm.hostname = "slave2.puppet"
      # slave.vm.network "forwarded_port", guest: 80, host: 8081
  
      slave.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "playbook.yaml"
        ansible.become = true
      end
    end
    
    config.vm.define "master.puppet", primary: true do |master|
      master.vm.network "private_network", ip: "192.168.210.151"
      master.vm.hostname = "master.puppet"
      master.vm.provider("virtualbox") { |vb| vb.memory = 1024 }
  
      master.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "playbook.yaml"
        ansible.limit = 'all'
        ansible.inventory_path = "inventory"
      end
    end
end 