---
- name: --= Jenkins =--
  hosts: jenkins.vm
  become: yes
  roles:
    - jenkins
    
- name: --= Nexus =--
  hosts: nexus.vm
  become: yes

  tasks:
  - name: Add key
    apt_key:
      url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public


  - name: Add repository
    apt_repository:
      repo: deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ buster main
      state: present
      update_cache: true

  - name: Install Java
    apt:
      name: adoptopenjdk-8-hotspot
      state: present

  - name: Install and config Nexus
    include_role:
      name: ansible-thoteam.nexus3-oss
    vars:
      nexus_timezone: 'Europe/Minsk'
      nexus_min_heap_size: "1024M"
      nexus_admin_password: 'admin'
      nexus_delete_default_repos: True
      nexus_local_users:
        - username: uploader
          first_name: Jenkins
          last_name: CI
          email: support@company.com
          password: "uploader"
          roles:
            - nx-admin
      nexus_config_raw: true
      nexus_repos_raw_hosted:
        - name: word-cloud-build
          version_policy: release
          write_policy: allow_once
          blob_store: default

- name: --= Slave's =--
  hosts:
    - staging.vm
    - production.vm
  become: yes

  tasks:

    - name: Create dir for service
      ansible.builtin.file:
        path: "/opt/wordcloud/"
        state: directory
        owner: vagrant
        group: vagrant
        mode: 0755

    - name: Create service
      copy:
        dest: "/etc/systemd/system/wordcloud.service"
        content: |
            [Unit]
            Description=Word Cloud Generator
            
            [Service]
            WorkingDirectory=/opt/wordcloud
            ExecStart=/opt/wordcloud/word-cloud-generator
            Restart=always
            
            [Install]
            WantedBy=multi-user.target

    - name: Just force systemd to reread configs
      ansible.builtin.systemd:
        daemon_reexec: yes

