Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    
    config.vm.define "nexus.vm" do |nexus|
      nexus.vm.network "private_network", ip: "192.168.210.152"
      nexus.vm.hostname = "nexus.vm"
      nexus.vm.provider("virtualbox"){ |vb| vb.memory = 2048 }
    end
  
    config.vm.define "staging.vm" do |staging|
      staging.vm.network "private_network", ip: "192.168.210.153"
      staging.vm.hostname = "staging.vm"
      staging.vm.provider("virtualbox"){ |vb| vb.memory = 256 }
    end
  
    config.vm.define "production.vm" do |production|
      production.vm.network "private_network", ip: "192.168.210.154"
      production.vm.hostname = "production.vm"
      production.vm.provider("virtualbox"){ |vb| vb.memory = 256 }
    end

    config.vm.define "jenkins.vm", primary: true do |jenkins|
      jenkins.vm.network "private_network", ip: "192.168.210.151"
      jenkins.vm.hostname = "jenkins.vm"
      jenkins.vm.provider("virtualbox"){ |vb| vb.memory = 1024 }
      
      jenkins.vm.provision :file, source: '.vagrant/machines/nexus.vm/virtualbox/private_key', destination: '/home/vagrant/.ssh/private_key_nexus.vm'
      jenkins.vm.provision :file, source: '.vagrant/machines/staging.vm/virtualbox/private_key', destination: '/home/vagrant/.ssh/private_key_staging.vm'
      jenkins.vm.provision :file, source: '.vagrant/machines/production.vm/virtualbox/private_key', destination: '/home/vagrant/.ssh/private_key_production.vm'

      jenkins.vm.provision "shell", inline: <<-shell
        chmod =600 /home/vagrant/.ssh/private_key_nexus.vm
        chmod =600 /home/vagrant/.ssh/private_key_staging.vm
        chmod =600 /home/vagrant/.ssh/private_key_production.vm
      shell

      jenkins.vm.synced_folder  ".", "/vagrant"

      jenkins.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "playbook.yaml"
        ansible.limit = "all"
        ansible.become = true
        ansible.inventory_path = "inventory.yaml"
      end
    end
end