Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
    config.vm.synced_folder  ".", "/vagrant", disabled: false

    config.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
    end

    config.vm.define "slave1" do |slave|
        slave.vm.network "private_network", ip: "192.168.210.152"

        slave.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "slave.yaml"
            ansible.become = true
        end
    end

    config.vm.define "slave2" do |slave|
        slave.vm.network "private_network", ip: "192.168.210.153"

        slave.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "slave.yaml"
            ansible.become = true
        end
    end

    config.vm.define "master", primary: true do |master|
        master.vm.network "private_network", ip: "192.168.210.151"

        master.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "master.yaml"
            ansible.limit = 'all'
            ansible.inventory_path = "inventory"
        end
    end
end