---
- name: Master provision
  hosts: master

  tasks:
    - name: install packages
      apt:
        pkg:
        - apache2
        - php
        state: present

    - name: changing permissions for www
      file:
        path: /var/www
        mode: '755'

    - name: create dir php/
      file:
        path: /var/www/php
        state: directory
        mode: '755'

    - name: add listen port 81
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen 81'
        insertafter: '^Listen 80'
        line: Listen 81

    - name: create php site config
      copy:
        src: /vagrant/files/001-php-default.conf
        dest: /etc/apache2/sites-available/001-php-default.conf

    - name: enable php site
      shell: a2ensite 001-php-default

    - name: restart apache2
      service:
        name: apache2
        state: restarted

    - name: copy index.html
      copy:
        src: /vagrant/files/index.html
        dest: /var/www/html/index.html

    - name: copy index.php
      copy:
        src: /vagrant/files/index.php
        dest: /var/www/php/index.php

