Vagrant.configure("2") do |config|
    config.vm.box = "generic/debian11"
  
    config.vm.synced_folder ".", "/vagrant"

    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 81, host: 8081
  
    config.vm.provider "virtualbox" do |vb|
        vb.name = "02-1-ansible"
        vb.memory = "512"
    end

    config.vm.define "master", primary: true do |master|
        master.vm.provision "ansible_local" do |ansible|
            ansible.playbook = "master.yaml"
            ansible.become = true
            ansible.limit = 'all'
            ansible.inventory_path = "inventory"
        end
    end
end