Vagrant.configure("2") do |config|
  config.vm.hostname = "01-vagrant"
  config.vm.box = "generic/debian11"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 81, host: 8081

  config.vm.provider "virtualbox" do |vb|
      vb.name = "01-vagrant"
      vb.memory = "512"
  end

  config.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install -y apache2 php
      mkdir /var/www/php/
      chmod -R o+w /var/www/
      chmod -R o+w /etc/apache2/
  SHELL

  config.vm.provision "file", source: "./index.html", destination: "/var/www/html/"
  config.vm.provision "file", source: "./index.php", destination: "/var/www/php/"
  config.vm.provision "file", source: "./ports.conf", destination: "/etc/apache2/"
  config.vm.provision "file", source: "./000-default.conf", destination: "/etc/apache2/sites-available/"

  config.vm.provision "shell", inline: <<-SHELL
      chmod -R o-w /var/www/
      chmod -R o-w /etc/apache2/
  SHELL

  config.vm.provision "shell", inline: "sudo systemctl restart apache2"
end