---

- name: Copy credentials .xml file
  ansible.builtin.unarchive:
    src: "{{ jenkins_config_via }}/credentials.tar.gz"
    dest: /var/lib/jenkins/

- name: Jenkins reload
  ansible.builtin.systemd:
    name: jenkins.service
    state: restarted
  