apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wcg
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: development

  source:
    repoURL: https://github.com/arraktur/devops-hometasks.git
    targetRevision: "v.*"
    path: ""
    chart: wcg

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: wcg

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true