apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wcg-final
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: development

  source:
    repoURL: "https://arraktur.github.io/devops-hometasks/"
    targetRevision: "*"
    path: ""
    chart: wcg

  # Destination cluster and namespace to deploy the application
  destination:
    server: "https://kubernetes.default.svc"
    namespace: wcg

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true