---

- name: --= Nexus =--
  hosts: nexus.vm
  become: true

  tasks:
  - name: Add key
    apt_key:
      url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public

  - name: Add repository
    apt_repository:
      repo: deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ buster main
      state: present
      update_cache: true

  - name: Install Java
    apt:
      name: adoptopenjdk-8-hotspot
      state: present

  - name: Install and config Nexus
    include_role:
      name: ansible-thoteam.nexus3-oss
    vars:
      nexus_timezone: 'Europe/Minsk'
      nexus_admin_password: 'admin'
      nexus_delete_default_repos: True
      nexus_anonymous_access: false
      nexus_config_raw: true
      nexus_local_users:
      - username: uploader
        first_name: Nexus
        last_name: Uploader
        email: jenkins@gmail.com
        password: "uploader"
        roles:
          - nx-admin
      nexus_repos_raw_hosted:
      - name: word-cloud-build
        version_policy: release
        write_policy: allow_once
        blob_store: default
     

- name: --= Stage and Prod =--
  become: true
  hosts:
    - staging.vm
    - production.vm

  tasks:
  - name: Create directory
    ansible.builtin.file:
      path: /opt/wordcloud/
      state: directory
      owner: vagrant
      group: vagrant

  - name: Install jq
    become: true
    apt:
      name:
      - jq
      state: present

  - name: Create wordcloud.service
    ansible.builtin.copy:
      src: "roles/jenkins/files//wordcloud.service"
      dest: "/etc/systemd/system/wordcloud.service"

- name: --= Jenkins =--
  hosts: jenkins.vm
  become: true
  roles:
  - jenkins