name: 10-github-action

on:
  push:
  workflow_dispatch:

env:
  OWNER: '${{ github.repository_owner }}' 
  
jobs:
  wcg:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACTION_TOKEN }}     
      - name: Set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}       
      - name: Push Docker image
        run: |
          docker build -t ghcr.io/${{ env.OWNER_LC }}/wcg:${{ github.sha }} -t  ghcr.io/${{ env.OWNER_LC }}/wcg:latest -f ./07-docker/Dockerfile.multi .
          docker push ghcr.io/${OWNER_LC}/wcg:${{ github.sha }}
          docker push ghcr.io/${OWNER_LC}/wcg:latest
